[package]
name = "seafloor"
version = "0.1.0"
authors = ["Jin <bluevortex002@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
h2 = "0.3.0"
smol = "1.2.5"